// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package client

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Ability defines model for Ability.
type Ability struct {
	// The name of the ability.
	Name *string `json:"name,omitempty"`

	// The URL of the ability's details.
	Url *string `json:"url,omitempty"`
}

// AffectingMove defines model for AffectingMove.
type AffectingMove struct {
	// The change in the stat caused by the move.
	Change int  `json:"change"`
	Move   Move `json:"move"`
}

// AffectingNature defines model for AffectingNature.
type AffectingNature struct {
	// The change in the stat caused by the nature.
	Change int    `json:"change"`
	Nature Nature `json:"nature"`
}

// Characteristic defines model for Characteristic.
type Characteristic struct {
	// The URL of the characteristic's details.
	Url *string `json:"url,omitempty"`
}

// Flavor defines model for Flavor.
type Flavor struct {
	// The name of the flavor.
	Name *string `json:"name,omitempty"`

	// The URL of the flavor's details.
	Url *string `json:"url,omitempty"`
}

// Generation defines model for Generation.
type Generation struct {
	// The name of the generation.
	Name *string `json:"name,omitempty"`

	// The URL of the generation's details.
	Url *string `json:"url,omitempty"`
}

// Move defines model for Move.
type Move struct {
	// The name of the move.
	Name *string `json:"name,omitempty"`

	// The URL of the move's details.
	Url *string `json:"url,omitempty"`
}

// MoveBattleStyle defines model for MoveBattleStyle.
type MoveBattleStyle struct {
	// The name of the move battle style.
	Name *string `json:"name,omitempty"`

	// The URL of the move battle style's details.
	Url *string `json:"url,omitempty"`
}

// MoveDamageClass defines model for MoveDamageClass.
type MoveDamageClass struct {
	// The name of the move damage class.
	Name *string `json:"name,omitempty"`

	// The URL of the move damage class's details.
	Url *string `json:"url,omitempty"`
}

// MoveLearnMethod defines model for MoveLearnMethod.
type MoveLearnMethod struct {
	// The name of the move learn method.
	Name *string `json:"name,omitempty"`

	// The URL of the move learn method's details.
	Url *string `json:"url,omitempty"`
}

// Nature defines model for Nature.
type Nature struct {
	// The name of the nature.
	Name *string `json:"name,omitempty"`

	// The URL of the nature's details.
	Url *string `json:"url,omitempty"`
}

// NatureDetails defines model for NatureDetails.
type NatureDetails struct {
	DecreasedStat Stat   `json:"decreased_stat"`
	HatesFlavor   Flavor `json:"hates_flavor"`

	// The ID of the nature.
	Id            int    `json:"id"`
	IncreasedStat Stat   `json:"increased_stat"`
	LikesFlavor   Flavor `json:"likes_flavor"`

	// The move battle style preferences influenced by the nature.
	MoveBattleStylePreferences []struct {
		// The preference for a move under high HP conditions.
		HighHpPreference int `json:"high_hp_preference"`

		// The preference for a move under low HP conditions.
		LowHpPreference int             `json:"low_hp_preference"`
		MoveBattleStyle MoveBattleStyle `json:"move_battle_style"`
	} `json:"move_battle_style_preferences"`

	// The name of the nature.
	Name string `json:"name"`

	// The changes in Pokeathlon stats caused by the nature.
	PokeathlonStatChanges []struct {
		// The maximum amount of change in the Pokeathlon stat.
		MaxChange      int            `json:"max_change"`
		PokeathlonStat PokeathlonStat `json:"pokeathlon_stat"`
	} `json:"pokeathlon_stat_changes"`
}

// PokeathlonStat defines model for PokeathlonStat.
type PokeathlonStat struct {
	// The name of the Pokeathlon stat.
	Name *string `json:"name,omitempty"`

	// The URL of the Pokeathlon stat's details.
	Url *string `json:"url,omitempty"`
}

// PokemonDetails defines model for PokemonDetails.
type PokemonDetails struct {
	// The abilities of the Pokemon.
	Abilities *[]struct {
		Ability *Ability `json:"ability,omitempty"`

		// Indicates if the ability is hidden.
		IsHidden *bool `json:"is_hidden,omitempty"`

		// The slot number of the ability.
		Slot *int `json:"slot,omitempty"`
	} `json:"abilities,omitempty"`

	// The base experience gained when defeating the Pokemon.
	BaseExperience *int `json:"base_experience,omitempty"`

	// The forms of the Pokemon.
	Forms *[]PokemonForm `json:"forms,omitempty"`

	// The game indices of the Pokemon.
	GameIndices *[]struct {
		// The game index of the Pokemon.
		GameIndex int     `json:"game_index"`
		Version   Version `json:"version"`
	} `json:"game_indices,omitempty"`

	// The height of the Pokemon in decimetres.
	Height *int `json:"height,omitempty"`

	// The ID of the Pokemon.
	Id *int `json:"id,omitempty"`

	// Indicates if the Pokemon is the default form.
	IsDefault *bool `json:"is_default,omitempty"`

	// The URL for accessing the Pokemon's location area encounters.
	LocationAreaEncounters *string `json:"location_area_encounters,omitempty"`

	// The moves of the Pokemon.
	Moves *[]struct {
		Move struct {
			// The name of the move.
			Name string `json:"name"`

			// The URL of the move's details.
			Url string `json:"url"`
		} `json:"move"`
		VersionGroupDetails []struct {
			// The level at which the move is learned.
			LevelLearnedAt  int             `json:"level_learned_at"`
			MoveLearnMethod MoveLearnMethod `json:"move_learn_method"`
			VersionGroup    VersionGroup    `json:"version_group"`
		} `json:"version_group_details"`
	} `json:"moves,omitempty"`

	// The name of the Pokemon.
	Name *string `json:"name,omitempty"`

	// The order of the Pokemon.
	Order *int `json:"order,omitempty"`

	// The past types of the Pokemon.
	PastTypes *[]struct {
		Generation Generation `json:"generation"`
		Types      []struct {
			// The slot number of the type.
			Slot *int  `json:"slot,omitempty"`
			Type *Type `json:"type,omitempty"`
		} `json:"types"`
	} `json:"past_types,omitempty"`
	Sprites *SpriteImages `json:"sprites,omitempty"`

	// The stats of the Pokemon.
	Stats *[]struct {
		// The base stat value.
		BaseStat int `json:"base_stat"`

		// The effort points gained when defeating the Pokemon.
		Effort int  `json:"effort"`
		Stat   Stat `json:"stat"`
	} `json:"stats,omitempty"`

	// The types of the Pokemon.
	Types *[]struct {
		// The slot number of the type.
		Slot int  `json:"slot"`
		Type Type `json:"type"`
	} `json:"types,omitempty"`

	// The weight of the Pokemon in hectograms.
	Weight *int `json:"weight,omitempty"`
}

// PokemonForm defines model for PokemonForm.
type PokemonForm struct {
	// The name of the Pokemon form.
	Name *string `json:"name,omitempty"`

	// The URL of the Pokemon form's details.
	Url *string `json:"url,omitempty"`
}

// SpriteImages defines model for SpriteImages.
type SpriteImages struct {
	// The URL of the default back sprite image.
	BackDefault *string `json:"back_default,omitempty"`

	// The URL of the female back sprite image.
	BackFemale *string `json:"back_female,omitempty"`

	// The URL of the shiny back sprite image.
	BackShiny *string `json:"back_shiny,omitempty"`

	// The URL of the shiny female back sprite image.
	BackShinyFemale *string `json:"back_shiny_female,omitempty"`

	// The URL of the default front sprite image.
	FrontDefault string `json:"front_default"`

	// The URL of the female front sprite image.
	FrontFemale *string `json:"front_female,omitempty"`

	// The URL of the shiny front sprite image.
	FrontShiny *string `json:"front_shiny,omitempty"`

	// The URL of the shiny female front sprite image.
	FrontShinyFemale *string `json:"front_shiny_female,omitempty"`
	Other            *struct {
		DreamWorld struct {
			// The URL of the dream world front sprite image.
			FrontDefault string `json:"front_default"`

			// The URL of the dream world female front sprite image.
			FrontFemale *string `json:"front_female,omitempty"`
		} `json:"dream_world"`
		Home struct {
			// The URL of the home front sprite image.
			FrontDefault string `json:"front_default"`

			// The URL of the home female front sprite image.
			FrontFemale *string `json:"front_female,omitempty"`

			// The URL of the shiny home front sprite image.
			FrontShiny *string `json:"front_shiny,omitempty"`

			// The URL of the shiny home female front sprite image.
			FrontShinyFemale *string `json:"front_shiny_female,omitempty"`
		} `json:"home"`
		OfficialArtwork struct {
			// The URL of the official artwork front sprite image.
			FrontDefault string `json:"front_default"`

			// The URL of the shiny official artwork front sprite image.
			FrontShiny *string `json:"front_shiny,omitempty"`
		} `json:"official_artwork"`
	} `json:"other,omitempty"`
}

// Stat defines model for Stat.
type Stat struct {
	// The name of the stat.
	Name *string `json:"name,omitempty"`

	// The URL of the stat's details.
	Url *string `json:"url,omitempty"`
}

// StatAffectingMoves defines model for StatAffectingMoves.
type StatAffectingMoves struct {
	// The moves that decrease the stat.
	Decrease []AffectingMove `json:"decrease"`

	// The moves that increase the stat.
	Increase []AffectingMove `json:"increase"`
}

// StatAffectingNatures defines model for StatAffectingNatures.
type StatAffectingNatures struct {
	// The natures that decrease the stat.
	Decrease []AffectingNature `json:"decrease"`

	// The natures that increase the stat.
	Increase []AffectingNature `json:"increase"`
}

// StatDetails defines model for StatDetails.
type StatDetails struct {
	AffectingMoves   StatAffectingMoves   `json:"affecting_moves"`
	AffectingNatures StatAffectingNatures `json:"affecting_natures"`

	// The characteristics related to the stat.
	Characteristics []Characteristic `json:"characteristics"`

	// The game index of the stat.
	GameIndex int `json:"game_index"`

	// The ID of the stat.
	Id int `json:"id"`

	// Indicates if the stat is only used in battles.
	IsBattleOnly    bool            `json:"is_battle_only"`
	MoveDamageClass MoveDamageClass `json:"move_damage_class"`

	// The name of the stat.
	Name string `json:"name"`
}

// Type defines model for Type.
type Type struct {
	// The name of the Pokemon type.
	Name *string `json:"name,omitempty"`

	// The URL of the type's details.
	Url *string `json:"url,omitempty"`
}

// Version defines model for Version.
type Version struct {
	// The name of the version.
	Name *string `json:"name,omitempty"`

	// The URL of the version's details.
	Url *string `json:"url,omitempty"`
}

// VersionGroup defines model for VersionGroup.
type VersionGroup struct {
	// The name of the version group.
	Name *string `json:"name,omitempty"`

	// The URL of the version group's details.
	Url *string `json:"url,omitempty"`
}

// IdPathParam defines model for IdPathParam.
type IdPathParam string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetNatureDetails request
	GetNatureDetails(ctx context.Context, id IdPathParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPokemonDetails request
	GetPokemonDetails(ctx context.Context, id IdPathParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetStatDetails request
	GetStatDetails(ctx context.Context, id IdPathParam, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetNatureDetails(ctx context.Context, id IdPathParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetNatureDetailsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPokemonDetails(ctx context.Context, id IdPathParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPokemonDetailsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetStatDetails(ctx context.Context, id IdPathParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStatDetailsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetNatureDetailsRequest generates requests for GetNatureDetails
func NewGetNatureDetailsRequest(server string, id IdPathParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/nature/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPokemonDetailsRequest generates requests for GetPokemonDetails
func NewGetPokemonDetailsRequest(server string, id IdPathParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pokemon/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetStatDetailsRequest generates requests for GetStatDetails
func NewGetStatDetailsRequest(server string, id IdPathParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stat/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetNatureDetails request
	GetNatureDetailsWithResponse(ctx context.Context, id IdPathParam, reqEditors ...RequestEditorFn) (*GetNatureDetailsResponse, error)

	// GetPokemonDetails request
	GetPokemonDetailsWithResponse(ctx context.Context, id IdPathParam, reqEditors ...RequestEditorFn) (*GetPokemonDetailsResponse, error)

	// GetStatDetails request
	GetStatDetailsWithResponse(ctx context.Context, id IdPathParam, reqEditors ...RequestEditorFn) (*GetStatDetailsResponse, error)
}

type GetNatureDetailsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NatureDetails
}

// Status returns HTTPResponse.Status
func (r GetNatureDetailsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetNatureDetailsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPokemonDetailsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PokemonDetails
}

// Status returns HTTPResponse.Status
func (r GetPokemonDetailsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPokemonDetailsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetStatDetailsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *StatDetails
}

// Status returns HTTPResponse.Status
func (r GetStatDetailsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStatDetailsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetNatureDetailsWithResponse request returning *GetNatureDetailsResponse
func (c *ClientWithResponses) GetNatureDetailsWithResponse(ctx context.Context, id IdPathParam, reqEditors ...RequestEditorFn) (*GetNatureDetailsResponse, error) {
	rsp, err := c.GetNatureDetails(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetNatureDetailsResponse(rsp)
}

// GetPokemonDetailsWithResponse request returning *GetPokemonDetailsResponse
func (c *ClientWithResponses) GetPokemonDetailsWithResponse(ctx context.Context, id IdPathParam, reqEditors ...RequestEditorFn) (*GetPokemonDetailsResponse, error) {
	rsp, err := c.GetPokemonDetails(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPokemonDetailsResponse(rsp)
}

// GetStatDetailsWithResponse request returning *GetStatDetailsResponse
func (c *ClientWithResponses) GetStatDetailsWithResponse(ctx context.Context, id IdPathParam, reqEditors ...RequestEditorFn) (*GetStatDetailsResponse, error) {
	rsp, err := c.GetStatDetails(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStatDetailsResponse(rsp)
}

// ParseGetNatureDetailsResponse parses an HTTP response from a GetNatureDetailsWithResponse call
func ParseGetNatureDetailsResponse(rsp *http.Response) (*GetNatureDetailsResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetNatureDetailsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NatureDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetPokemonDetailsResponse parses an HTTP response from a GetPokemonDetailsWithResponse call
func ParseGetPokemonDetailsResponse(rsp *http.Response) (*GetPokemonDetailsResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPokemonDetailsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PokemonDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetStatDetailsResponse parses an HTTP response from a GetStatDetailsWithResponse call
func ParseGetStatDetailsResponse(rsp *http.Response) (*GetStatDetailsResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStatDetailsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StatDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Nature Details by ID
	// (GET /nature/{id})
	GetNatureDetails(ctx echo.Context, id IdPathParam) error
	// Get Pokemon Details by ID or Name
	// (GET /pokemon/{id}/)
	GetPokemonDetails(ctx echo.Context, id IdPathParam) error
	// Get Stat Details
	// (GET /stat/{id})
	GetStatDetails(ctx echo.Context, id IdPathParam) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetNatureDetails converts echo context to params.
func (w *ServerInterfaceWrapper) GetNatureDetails(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdPathParam

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetNatureDetails(ctx, id)
	return err
}

// GetPokemonDetails converts echo context to params.
func (w *ServerInterfaceWrapper) GetPokemonDetails(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdPathParam

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPokemonDetails(ctx, id)
	return err
}

// GetStatDetails converts echo context to params.
func (w *ServerInterfaceWrapper) GetStatDetails(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdPathParam

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetStatDetails(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/nature/:id", wrapper.GetNatureDetails)
	router.GET(baseURL+"/pokemon/:id/", wrapper.GetPokemonDetails)
	router.GET(baseURL+"/stat/:id", wrapper.GetStatDetails)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RbW4/jtvX/KoT+fyAvtrWz2fTBb9sssh0g2Q6y27ykgUBLRxazEqmSlD3Gwt+94EV3",
	"yrp5pu2bLZG/c+XhOeTRNy9kWc4oUCm8/TcvxxxnIIHrf4/RE5bJk3qm/kYgQk5ySRj19t6XBNDjB8Ri",
	"JBNAHAQreAg7b+MR9TrHMvE2HsUZeHuPRN7G4/CvgnCIvL3kBWw8ESaQYYUsL7kaJSQn9Ohdr1c1WOSM",
	"CtCMfGLyJ1bQyM2FwgUhIaq4QGcsEGUSxWrWzlOAhpqGe38gKZEX9ROecZanoH5aVtkJ+JGzs7fxCp56",
	"ey+RMhd738/ZV8A52YXMxznxT299bHD8v/zge9eNl3OWA5fE8GzgXPyqN6XeLIRSW0cJlrwL4B+//tyZ",
	"/51AEUhMUqGQYsYzLL29RugBX6sn7PAnhFKReh/HEEpCj7+wk+a6LUuYYHockMa8Q4RqfoTEEoW4EBCh",
	"w0U/ythJu0Wl6u1DxQGhEo7AFQuZpfz/HGJv7/2fX3umb23na+6Md5Su9HvJnEX445Z0n7As+L3loxq0",
	"YcGGULQieEssy9agYBbFJdqPCeY4lMCJkCTsSzbFh8IWRtuVKqPdWAbt+f6Dv8gFf0rxifG+BNPWUaxn",
	"tzn+nJPwsnRhGcD5yjgA55etmb1UFR+BAseGL1eIOlbvt6cJYaoe7i8PVDXI4lhVQ6wNV+4oNU2QXjjy",
	"VLRPlwql4OZ7iZrlv/vBXyz9X7GUKXyWl3SVItBB4yChgNrMYylx+HWNWlrgy3S0NRBbDbF0OSl9fcAZ",
	"PsKPKRZilb4ijYNCBdQWJE8ugoR4lSO14BdqzEBsNYT/drnGfgbM6S8gExa5oxAcjxOCj+YpVVjbTIMp",
	"nhbGIK0ijYUM1m6VsptIayPSUGYxTbA6hajNLLAQi3cvAzjfg8w8/+07f4UWPhiafWVEEHLAAqJApVFj",
	"WdFnNea68RIsQQRxlR7cmmOTiOtGVRwjJYtD6c7ElNAlXKfk6wKulV8GJuYFOuYFOYcYONCwVGFXoF6k",
	"RY0piNA4LdRPR7pKJGQOKyXkmARJ3qDsJly/RzHjCBtOChoBRwoD/e0JhYxGRM0R7vw4Zee1pFJ2nkKp",
	"p9kptUZzl+1m533WNy7VuSi7Enn7AHOOL6ZyWBo4EswjZ+DQy10mKaPakwNTX4hbZY9yIPRUzdPljxis",
	"fwYcKsPPwa0KK8PPJCsyhDNWUKlEa9dcHfpu+3aEG7NujWkWbMe4DZb70OPm66Dp0w9t0E03BvbCSyfe",
	"dQLJsBHHYoeL6Y4SFm5eDvM0drEcIFq6i3WQ529ntbK2CmBpAqn4yBgd3NfMIQwZWkrV66ZcmSmkBpYM",
	"rk+obnlxeZCldikRJCSKgPZ5eKQRCZVTIdI6NEJEIDOnsaQOjKWAqYIUKZNuidQbRIvsAHz4IKtanNcJ",
	"4e6ABQTwnAMnw9uAGoTqQeiICYUInROgKIIYsCT02NVwP1QoBxgwlX51y0xjMSVj9CfGM5eIR5xBQJQt",
	"hhxFjUB2xHRfKXHh+TYqPDsw+9o5ARf25OGWsL/ZYd1Y1+Cmxpqy4SVAjsmAv5l3HfbV9hBBSDKQHAZ2",
	"/fEs8KYuiAgiiHGRygmrqmJL6L92onYp9/pKWahPQwLMAQdAQ7X92aN3d1zUyU8YghAdR/9OoBINKTRU",
	"o43XM2bruJFeznDG7A4nM3c6hxmN8023tbuzGupyVuvIwZGzIg+ieiMYUEMKJ0gDXWBCFOABt9ajEJbo",
	"nJAwqQtTIpCdeiOX1SOCrCrQx3LZZj3flWjiYv+ox/YS4a6sLga7BGfnUNqxhgxxv4S6Hw5qN2Q8Au6G",
	"0K8mhZQcCxmoxwPrTb1H+v2MHaB1XnzLkI2TZauiW148KwFQYG6RzZPbjH1RYyZkCt3dppanFGeKL4ic",
	"EwmjG/pnPewxwyrBVtNU9TOgEF0YTbaYTnfKOmUg0dFXTSecFgNqhThmfADAvEM5I1SKpXnS9OOOjlVq",
	"6SouLdoU49xYHDPXxX/Cf5t60PTt/CmSn2+kQOehFCiBULIjx5mYmns381Tnye6hSA9Y4IJPON/NDdhW",
	"7baqvlp4tFsK1MmW5teLJcjaA93W2nes3/DrcGrYYavMBNUkZEIPIgp4SmqmKcWQ4RTG7yz1sBV0RELo",
	"ZZSMHrWWylSZDLE1ksWcUTnbWHrWQlrzzLWG0hyDraazyGTLqDKZgKMXIOKAs+DMeNq9k+oYuQpYHJ93",
	"RyKT4lAI4CGjEqjchSzT1fr7p0ff5gJ+hoUEXv21cc3XnPia8FYT9h924nT0urZ+SYqGhiXcC7Az/Vvh",
	"Io37Gj7eIrfcIzoba1tk19aaMLPrvJ6LKIr+wy6nL+8bmlTlFE2KNh68CEGN7aL3snIasi1pVy4BBfsa",
	"vm/ovG6QXy3bgki/Vs7Zi5vFMQkJTgPM5Znxr6+70EvqW0v9dZZgj2pzOa5cECU2stiv5q13ITzTfTrD",
	"mymF3TYcDjYKM+605RVbv9xSJTkVMKHYKi+xFhZZndvTecVV/wZuQVElsWy1Gt9oErl1HC0TLFE5sCVa",
	"Q7vllfP2odmHa3VedteMabzREKMkmnQP1G6mdtT55ZXvqIjlwDERXRIemPboqQLeT77u5XcpbH33Pbg+",
	"Oo3as73DCPM/4x9l3/dcD2mJ+V/uI0MyrvCS4Xv4kmhQXWiNnV12otF10wChtRNOhikd97rx2m3xw202",
	"zUGIQ4olREiylj0n6bzzLcCNK+jpV8U9h3pYds06EUeUDSyMppcJd676jJwIpIYj3ZREqG2GazeJxDgV",
	"4LqE1VdVpmc2CMv24LG7tGY38eSrpX5zTJKPZjPN1qHW1XpHVZue87s8ue+ULgW41t0Xewbu+BiBqznj",
	"QURB+g9vV58Qd87p5yUxatLaJOa3ukGirw0OUwKqvcVckcpZhMWKsPPvpIuP5SWywz1YGm0FSU/Apytm",
	"q693/e/XqgdpnLVKMijrVKU3ThozF00iVAjDFP09B/r+6RGJHEISE9vPETOObKm4+6e+5yRShw/7sNFn",
	"s/cedm92b3SNnAPFOfH23vf60UZ/kalVWO7n30h0NdfHjhLxV5CcgMpEjdQ6tBqpdZPJgRUS4YpVm5Po",
	"m8sIMYqIFOjxg1KVsp6e9Bh5e+8jyHaXeOdTz7dv3uisxdTJelfP89Tqwv9TmIVXfzo6/l1dSUjboC3k",
	"50I308RFikom0JlI04phZtdGv268d2/eDdGshPCrj1X1V6dFlmF+MYKXkJYjdLigxw/KoPgoVLC3udIf",
	"uk2g/hD3dzfFeojf/FD3qqZXhwfKxv7djFzG4I6VEePoE87Aae1O8+QLmrtDaa69S+HuafASs2XxUl0N",
	"y9txdzG9PiS4y9q2CUvPpM0k/AXt2SQz15hq7l0tqQFroUvD6VOd1VZT1ICfyskju6Sa8e8AAAD//yEb",
	"w8O5PwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

