name: Regenerate Client

on:
  push:
    branches: ["main"]

  workflow_dispatch:

env:
  GO_GEN_CLIENT_FILE: client/client.gen.go
  OPENAPI_GEN_FILE: openapi.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: install-oapi-codegen
        run: make oapi-codegen-install
      - name: set-up-diff-test
        run: |-
          mkdir tmp
          cp openapi.yaml tmp/openapi.yaml
      - name: generate-the-client
        run: make oapi-codegen-generate
      - name: run-diff-test
        run: |-
          diff docs/openapi.yaml tmp/openapi.yaml
          retVal=$?
          if [ $retVal -ne 0 ]; then
            # if diff doesn't return 0, error
            exit 2
          fi
      - name: check-on-failures
        # if no changes, just exit
        if: steps.run-diff-test.outcome != 'success'
        run: exit 0
      - name: create-pull-request
        if: steps.run-diff-test.outcome == 'success'
        run: |-
          git config --global user.email "jessicanatashamail@gmail.com"
          git config --global user.name "oapi-codegen"
          git add -A 
          git commit -m "chore: automated update of client code"
          git push
